AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Castle Backend - Serverless Express API

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name
  
  CorsOrigin:
    Type: String
    Default: "*"
    Description: CORS allowed origin
  
  SupabaseUrl:
    Type: String
    Description: Supabase project URL
  
  SupabaseKey:
    Type: String
    Description: Supabase anon key
  
  ApiKeyThrottleRate:
    Type: Number
    Default: 10
    Description: API key throttle rate limit (requests per second)
  
  ApiKeyThrottleBurst:
    Type: Number
    Default: 50
    Description: API key throttle burst limit
  
  ApiKeyQuotaLimit:
    Type: Number
    Default: 1000
    Description: API key monthly quota limit

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 256
    Architectures:
      - arm64
    Environment:
      Variables:
        NODE_ENV: !Ref Environment

Resources:
  CastleBackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "castle-backend-${Environment}"
      CodeUri: ./
      Handler: lambda.handler
      Environment:
        Variables:
          CORS_ORIGIN: !Ref CorsOrigin
          SUPABASE_URL: !Ref SupabaseUrl
          SUPABASE_KEY: !Ref SupabaseKey
      Events:
        ApiProxy:
          Type: Api
          Properties:
            RestApiId: !Ref CastleBackendApi
            Path: /{proxy+}
            Method: ANY
        ApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref CastleBackendApi
            Path: /
            Method: ANY

  CastleBackendApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "castle-backend-api-${Environment}"
      StageName: !Ref Environment
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: !Sub "Usage plan for castle-backend-api-${Environment}"
          Quota:
            Limit: !Ref ApiKeyQuotaLimit
            Period: MONTH
          Throttle:
            RateLimit: !Ref ApiKeyThrottleRate
            BurstLimit: !Ref ApiKeyThrottleBurst
      EndpointConfiguration:
        Type: REGIONAL

Outputs:
  ApiGatewayUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${CastleBackendApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"
  
  LambdaFunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt CastleBackendFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-LambdaArn"
  
  ApiKey:
    Description: API Key for accessing the API
    Value: !Ref CastleBackendApiApiKey
    Export:
      Name: !Sub "${AWS::StackName}-ApiKey"
  
  UsagePlan:
    Description: Usage Plan for API throttling and quotas
    Value: !Ref CastleBackendApiUsagePlan
    Export:
      Name: !Sub "${AWS::StackName}-UsagePlan"
